### ISSUE TITLE
more langs?

### ISSUE THREAD

**Issue by lvm** [toplap/awesome-livecoding#2]
Keep lurking to find out unlisted languages

**Comment by celestebetancur** [comment]
https://github.com/essteban/CHmUsiCK  library to make chucK a 'more algorave like' language. :)

**Comment by lvm** [comment]
Cool! 
Where do you feel this should go? may be in "Libraries and tools" (because it extends a language)?

**Comment by celestebetancur** [comment]
Definitely.

**Comment by lvm** [comment]
done!

**Comment by celestebetancur** [comment]
that was fast.

**Comment by moxuse** [comment]
https://hexler.net/software/kodelife tool for livecoding visuals on glsl shader by hexler.

**Comment by lvm** [comment]
added, also added `glslViewer` by @patriciogonzalezvivo

**Comment by keszegh** [comment]
in [Gideros SDK](http://giderosmobile.com/) (which uses the lua language) one can also live code using the [ZeroBrane Studio](http://studio.zerobrane.com/) editor, see
https://studio.zerobrane.com/documentation#live-coding

**Comment by lvm** [comment]
@keszegh 
Great. Where do you think this fits? "Libraries and tools" sounds ok?
If you agree, please go ahead a create a PR with this changes !

**Comment by keszegh** [comment]
@lvm , done, with a bit of redundancy mentioning zerobrane studio several times, feel free to remove some of them.

**Comment by lvm** [comment]
good! let's continue in the PR.

**Comment by ddovod** [comment]
Hello guys.
Please consider adding these 2 libraries as implementing hot code reload approach for any c++ projects:
- [blink](https://github.com/crosire/blink) - A tool which allows you to edit source code of any Windows C++ project live at runtime
- [jet-live](https://github.com/ddovod/jet-live) - c++ hot code reload for linux and macos

Thanks!

**Comment by lvm** [comment]
Hi @ddovod 
both libs look really good, if you're comfortable with github and creating pull requests, please go ahead and create one adding them both.  
if you need any help, please ask :+1:

**Comment by ddovod** [comment]
Sure, thank you! Here it is #35

**Comment by lvm** [comment]
will close this issue. if there's anything new, please create PR.
