### ISSUE TITLE
Tag languages as being for audio or visuals

### ISSUE THREAD

**Issue by hellocatfood** [toplap/awesome-livecoding#25]
I think the list of languages should be separated to those for livecoding visuals and audio. Or, to avoid duplication (e.g. Pure Data can be used for audio and visuals) there should be a tag to state whether the language is for audio or visuals.

**Comment by lvm** [comment]
Hi there, sorry for the delayed response.  
Haven't thought of that before, but yes, agree.   
Any suggestion which tags to use?  do `audio` `visual` (to keep things simple) work for you?

btw, i'm @mauro in the livecoding slack, I'll probably reply quicker over there.

**Comment by hellocatfood** [comment]
Yeah, I think that'll do nicely! I'll respond on there too.

**Comment by tuborgman** [comment]
I think it would also be beneficial to include something like last_updated date - it would help to figure out what is hot.

**Comment by itsdeadguy** [comment]
Or, more importantly, what is still alive and buildable

**Comment by tuborgman** [comment]
Exactly!

**Comment by lvm** [comment]
Hi,
Pretty much everything that's listed is still alive and **buildable**.  
About last_updated, you're one hyperlink away from that data (since most project are hosted on a vcs repository which already has this information).
