### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by lvm** [toplap/awesome-livecoding#3]
probably could be useful to have an (or more) example of each lang.
text or recording of livecoding performance should be fine.

**Comment by azimut** [comment]
+1
Gather compositions examples (even on other languages) is time consuming when starting. Examples from the language creators themselves can be a good start. I found some here: https://github.com/brandm/music-coding-references

**Comment by lvm** [comment]
Yes, not only it's time consuming, the examples can become outdated too. 
The repository linked looks good but it's a bit messy, I'd rather dedicate time to gather videos (see the first paragraph) for each lang and build a (yet another) list under "Examples" perhaps.

**Comment by lvm** [comment]
since this issue hasn't made any progress in over a year, will close it now.
