### ISSUE TITLE
highlight samples used by each language

### ISSUE THREAD

**Issue by azimut** [toplap/awesome-livecoding#31]
Might be outside the scope of the list, but the idea behind is that each language comes with his own samples or the documentation relies on ones in particular. Giving each language his own "sound", might be highlighting them would change that and help people discover them. The ones I know:

https://github.com/tidalcycles/Dirt-Samples
https://github.com/samaaron/sonic-pi/tree/master/etc/samples
https://github.com/elihugarret/Moonlet/tree/master/Samples
https://github.com/Qirky/FoxDot/tree/master/FoxDot/snd
https://github.com/Tonejs/Tone.js/tree/dev/examples/audio
https://github.com/overtone/overtone/wiki/Buffers-and-audio-files

**Comment by lvm** [comment]
Sorry for the late response, I don't seem to be receiving notifications for this kind of stuff.
I see what you mean and i find this somehow interesting, but not entirely sure where to add this stuff. Perhaps working on a "awesome-samples" list (or may be a sub-list of this oone)? I surely add that to this list.
