### ISSUE TITLE
Display contributors

### ISSUE THREAD

**Issue by lvm** [toplap/awesome-livecoding#36]
I was wondering if is it a good thing to add contributors (avatars/link to their profile) in the readme.
On one hand, actually shows who they are and somehow shows a bit of gratitude for their work.
On the other hand, it's already available through the github web interface.

I think it would be a good addition, but also i'd like to know what others think.

Basically it'll look something like this:
![2019-02-07-195842_1920x1080_scrot](https://user-images.githubusercontent.com/34095/52448719-8a873300-2b13-11e9-9b6d-3a4e8b10f0d2.png)

Anyone can edit this in the future by running this command:
```
wget https://api.github.com/repos/toplap/awesome-livecoding/contributors -O - | \
    jq '.[] | " [<img src=#\(.avatar_url)# height=50 width=50>](\(.html_url)) "' | \
    sed -s 's,",,g; s,#,",g'
```

**Comment by lvm** [comment]
@yaxu @sicchio  @ddovod  @grz0zrg @charlieroberts @ajrussellaudio @hellocatfood @neuromancer85 @bobvanluijt  @claudeha @davidedc  @mortuosplango  @jcelerier  @merongivian @kostik1337 @theseanco  @smokris  @fand  @azimut  @keszegh  @paullucas  @iyzsong

Sorry to bother, but since you're the contributors listed, i think i need to ask you all:
how do you feel about this? Do you agree or prefer not to be shown?

thanks.

**Comment by yaxu** [comment]
Fine by me!

**Comment by grz0zrg** [comment]
Agree.

**Comment by keszegh** [comment]
sure, even though my contribution was insignificant.

**Comment by ajrussellaudio** [comment]
I've only made a small contribution here (1 commit, deleted 7 characters!) and it was months ago now, but I'm quite high up on the list. I think it's because my name starts with A, and we're sorted alphabetically after sorting by number of commits.

This isn't a problem for me, just pointing it out. I'm totally fine with appearing on the list.

**Comment by jcelerier** [comment]
no probs, whatever's the easiest for you

**Comment by lvm** [comment]
@ajrussellaudio 
> I've only made a small contribution here (1 commit, deleted 7 characters!) and it was months ago now, 

yeah, no problem. 😃 
i'm not sure how github api sorts people (from the ui you can choose but the public api doesn't seem to have the same options).

**Comment by merongivian** [comment]
Sure, thanks :)

**Comment by fand** [comment]
fine, thx😸

**Comment by claudeha** [comment]
fine by me

**Comment by neuromancer85** [comment]
Ok, no problem 👍

**Comment by davidedc** [comment]
✨FAMOUS AT LAST✨
![finally-famous](https://user-images.githubusercontent.com/769568/52555595-17671080-2de2-11e9-80b8-1ae93f1f3876.gif)

**Comment by ddovod** [comment]
Sure, no problem, thanks!

**Comment by mortuosplango** [comment]
Si, claro

**Comment by kostik1337** [comment]
Fine for me
