### ISSUE TITLE
Live coding music in the browser

### ISSUE THREAD

**Issue by petersalomonsen** [toplap/awesome-livecoding#47]
Just wanted to share my experiments with the new AudioWorklet technology and Webassembly for creating a synthesizer and sequencer in the browser, and programming the sequencer live using Javascript.

This is still very much work in progress, but has already been used for creating some stuff.

Demo video:
https://youtu.be/ZQUo2fZwUgw

Website:
https://petersalomonsen.com/webassemblymusic/livecodev1/

Sources of some full songs that can be pasted into the editor:

- https://github.com/petersalomonsen/javascriptmusic/blob/master/wasmaudioworklet/synth1/songs/livetest1.js ( or listen at soundcloud: https://soundcloud.com/psalomo/groove-is-in-the-code-webassembly-mix )

- https://github.com/petersalomonsen/javascriptmusic/blob/master/wasmaudioworklet/synth1/songs/goodtimes.js (or listen at soundcloud: https://soundcloud.com/psalomo/good-times )

sources for the full synth / sequencer / editor is in that same github repository.

**Comment by lvm** [comment]
Hi there,
There's a community you can join and share this kind of stuff here: https://talk.lurk.org/channel/general
If you want to add this to the list, you can create a Pull Request by forking/editing README.md 
[Here](https://github.com/toplap/awesome-livecoding/blob/master/contributing.md)'s a guide that might help. Let me know if you need any help.
