### ISSUE TITLE
Is this a new language though?

### ISSUE THREAD

**Issue by lvm** [toplap/awesome-livecoding#64]
https://github.com/toplap/awesome-livecoding/commit/996f2752f964ebda4d9151959fb7fab06ad2e294

-1 for me.

**Comment by yaxu** [comment]
I'd say it's a language, yes.. Can you explain your objection a bit more please?

**Comment by lvm** [comment]
its a tool to use bytebeat.

yet another.

**Comment by yaxu** [comment]
I think visual live coding software is probably underrepresented in the list
We could move it to libraries and tools along with pytebeat?

**Comment by lvm** [comment]
Sure, i'd move it to the libs and tools section.

**Comment by yaxu** [comment]
Ok done!

**Comment by lvm** [comment]
thanks!
