### ISSUE TITLE
"i-score" link is broken - looks like it's moved / renamed

### ISSUE THREAD

**Issue by znmeb** [toplap/awesome-livecoding#71]
I went to the "i-score" link on the README and got a "Hmmm ... we're having trouble finding that site" from Firefox. A little searching turned up this:

https://github.com/ossia/score

Is it "i-score" renamed, or is the Ossia "score" something different entirely?

[edit]

I went to the home page [https://ossia.io/](https://ossia.io/) and it does look like a useful graphical livecoding tool. If that's the case and it belongs in this list, does Iannix also belong? 

[https://www.iannix.org/en/](https://www.iannix.org/en/)

**Comment by lvm** [comment]
about i-score, i wouldn't know. perhaps @jcelerier can shed a light on this? (it was added by him [here](https://github.com/toplap/awesome-livecoding/commit/5e80c8036370501ca26fc577bc1b0f6b007ca7bf))

about iannix: i'd say yes, please create PR and i'll merge it.

thanks!

**Comment by jcelerier** [comment]
hi ! yes, `ossia score` is the new name of `i-score`

**Comment by znmeb** [comment]
Ossia Score looks really cool. I knew about IanniX from my studies of Xenakis but not Ossia Score until today.

**Comment by jcelerier** [comment]
made PR #73
