### ISSUE TITLE
Adding Gwion to the list of languages

### ISSUE THREAD

**Issue by fennecdjay** [toplap/awesome-livecoding#81]
[Gwion](https://github.com/Gwion/Gwion) is a language inspired by chuck and as such seems suited for livecoding.

Would you consider a PR including it in the language list?

**Comment by lvm** [comment]
Well it depends: does it have "live coding" capabilities or is it a music oriented language?

**Comment by fennecdjay** [comment]
I would say both, I don't see those as incompatible.

**Comment by lvm** [comment]
Go ahead then :dancers:

**Comment by lvm** [comment]
merged
