### ISSUE TITLE
Dark theme Toplap logo variant

### ISSUE THREAD

**Issue by Taink** [toplap/awesome-livecoding#99]
On GitHub's Dark theme, the toplap logo is not very visible:
![README top logo screenshot](https://user-images.githubusercontent.com/22330916/200578307-7a14ca52-e269-4fc8-afbd-bf625515590b.png)

GitHub recently introduced[^1] a way to specify theme context for images, which allows providing an alternative logo to dark theme users.

[^1]: See <https://github.blog/changelog/2022-08-15-specify-theme-context-for-images-in-markdown-ga/>

Here is an example, taken from their blog post:

```md
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/25423296/163456776-7f95b81a-f1ed-45f7-b7ab-8fa810d529fa.png">
  <img alt="Shows an illustrated sun in light color mode and a moon with stars in dark color mode." src="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
</picture>
```

**Comment by lvm** [comment]
Yeah, this is something I had in my mind for some time. Will appreciate any attempt to tackle this!
